ARG BASE_IMAGE=docker.pkg.github.com/virtocommerce/vc-platform/platform:3.2.1-d8d2ca70
FROM ${BASE_IMAGE}

# Install unzip wget python3
RUN apt-get update && apt-get install -y unzip
RUN apt-get update -qq && apt-get install -y wget
RUN apt-get update -qq && apt-get install -y python3

RUN mkdir -p /opt/virtocommerce/platform/wwwroot/cms-content/Themes
RUN mkdir -p /opt/virtocommerce/platform/wwwroot/Modules

WORKDIR /opt/virtocommerce/platform/Modules

COPY /install-modules.py .

COPY /platform.json .

RUN python3 install-modules.py

WORKDIR /opt/virtocommerce/platform

ENTRYPOINT ["dotnet", "VirtoCommerce.Platform.Web.dll"]